config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'mom_midwife_signup', to: 'pages#new_mom_midwife', as: :new_mom_midwife

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :midwives do
    resources :bookings
  end

  resources :bookings do
    resources :appointments, except: [:destroy]
    resources :messages, only: :create
  end

  resources :appointments, only: [:destroy]
  resources :moms do
    resources :notes, only: [:new, :create]
  end

  resources :notes, only: [:edit, :update, :destroy]

  get 'search', to: 'pages#search', as: :search
  get 'calendar', to: 'pages#calendar', as: :calendar
  get 'chatrooms', to: 'pages#chatrooms', as: :chatrooms
  patch 'bookings/:id/accepted', to: 'bookings#accepted', as: 'accepted'
  patch 'bookings/:id/cancelled', to: 'bookings#cancelled', as: 'cancelled'
  patch 'bookings/:id/cancelled_user', to: 'bookings#cancelled_user', as: 'cancelled_user'
  patch 'bookings/:id/appointments/:id/cancelled_appointment', to: 'appointments#cancelled_appointment', as: 'cancelled_appointment'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :mom
  belongs_to :midwife
  has_many :appointments, dependent: :destroy
  has_many :messages, dependent: :destroy

  enum status: {
    pending: 0,
    confirmed: 1,
    cancelled: 2
  }

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_mom, only: []
  before_action :set_booking, only: [ :accepted, :cancelled, :cancelled_user, :show]
  before_action :set_midwife, only: [:create]

  def accepted
    @booking.confirmed!
    redirect_to midwives_path, notice: "New request has been accepted"
  end

  def cancelled
    @booking.cancelled!
    redirect_to midwives_path
  end

  def cancelled_user
    @booking.cancelled!
    redirect_to search_path
  end

  def index
    if current_user.is_midwife?
      @bookings = Booking.where(midwife: current_user.midwife)
    else
      @bookings = Booking.where(mom: current_user.mom)
    end
  end

  def show
    @boooking = Booking.find(params[:id])
    @message = Message.new
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new
    @booking.mom = current_user.mom
    @booking.midwife = @midwife
    if @booking.save!
      redirect_to search_path
    else
      render 'midwives/show'
    end
  end

  def destroy
    @booking.destroy
    redirect_to root_path
  end

  private

  def set_mom
    @mom = Mom.find(params[:mom_id])
  end

  def set_midwife
    @midwife = Midwife.find(params[:midwife_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:mom_id, :midwife_id, :status)
  end
end

app/views/bookings/index.html.erb
<div>
  <% if current_user.is_midwife? %>
    <div class="container pb-5">
        <div class="background-card pb-0 mt-1 mb-2">
          <h2 style="font-weight: 500">Bookings</h2>
        </div>
        <% if !@bookings.empty? %>
          <% @bookings.each do |booking| %>
            <% unless booking.pending? %>
              <div class="inner-card" style="margin-bottom: 20px;">
                <%= link_to mom_path(booking.mom), class: "text-decoration-none text-dark" do %>
                  <div class="name-avatar">
                    <%= cl_image_tag booking.mom.photo.key , class: "avatar"%>
                      <h4><strong><%= booking.mom.user.first_name %> <%= booking.mom.user.last_name %></strong></h4>
                  </div>
                    <div class="border m-2"></div>
                  <div class="info-card">
                    <p><i class="fa-solid fa-baby" style="color:#FC9D9D"></i>  <%=  booking.mom.due_date %></p>
                    <p><i class="fa fa-map-marker" style="color:#FC9D9D"></i>  <%=  booking.mom.user.address %></p>
                  </div>
                <% end %>
                <%= link_to "Message", booking_path(booking), class: "btn btn-accept" %>
                <%= link_to "New Appointment", new_booking_appointment_path(booking), class: "btn btn-accept" %>
              </div>
            <% end %>
          <% end %>
    </div>
        <% else %>
          <div class="container">
            <div class="outer-card mb-5" id="midwife-card">
                <p>You currently have no patients</p>
                <%= link_to 'Home', midwives_path, class: "btn btn-accept" %>
            </div>
          </div>
        <% end %>
  <% else %>
    <div class="container">
      <div class="outer-card mt-3 mb-5" id="mom-card">
        <div class="background-card pb-0">
          <h2>Appointments</h2>
        </div>
        <% if !@bookings.empty? %>
          <% @bookings.each do |booking| %>
            <% unless booking.pending? %>
              <div class="inner-card pt-2">
                  <div class="name-avatar" style="align-items: end;">
                    <div class="picture-name">
                      <%= cl_image_tag booking.midwife.photo.key , class: "avatar-blueb"%>
                      <h4><%= booking.midwife.user.first_name %> <%= booking.midwife.user.last_name %></h4>
                    </div>
                  </div>
                    <div class="border"></div>
                  <div class="info-card">
                    <p><i class="fa-solid fa-star" style="color:#A3C7D6"></i> Speciality: <%=  booking.midwife.speciality %></p>
                    <p><i class="fa fa-clock" style="color:#A3C7D6"></i>    Appointments:
                    <% booking.appointments.each do |appointment| %>
                      <% unless appointment.cancelled? %>
                      <p><%= appointment.title %> <%= appointment.start_time.strftime(("%A, %d %b %Y %l:%M %p") ) %></p>
                      <div class="display-flexbox" style="justify-content: space-evenly;">
                      <%= link_to "Calendar", booking_appointments_path(booking), class: "btn btn-blue"%>
                      <%= link_to "Message", booking_path(booking), class: "btn btn-blue" %>
                      </div>
                      <% end %>
                    <% end %></p>
              </div>
            <% end %>
          <% end %>
      </div>
    </div>
        <% else %>
          <div class="container">
            <div class="outer-card mb-5" id="mom-card">
                <div class="inner-card">
                    <p>You currently have no midwife</p>
                </div>
                <%= link_to 'Home', midwives_path, class: "btn btn-accept" %>
            </div>
          </div>
        <% end %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<% if current_user.is_midwife? %>
  <div id= "midwife-background">
    <div class="header-chat">
    <%= cl_image_tag @booking.mom.photo.key , class: "avatar-large"%>
    <h1><%= @booking.mom.user.first_name %> <%= @booking.mom.user.last_name %></h1>
    </div>
  </div>
  <div class="container chatroom mb-5 pb-5" id="chatroom-midwife"
      data-controller="booking-subscription"
      data-booking-subscription-booking-id-value="<%= @booking.id %>">
    <div class="messages" data-booking-subscription-target="messages">
      <% @booking.messages.each do |message| %>
          <%= render "messages/message", message: message %>
      <% end %>
    </div>
      <%= simple_form_for [@booking, @message], html: { data: { action: "turbo:submit-end->booking-subscription#resetForm" }, class: "d-flex chatroom-form-container" } do |f| %>
        <%= f.input :content,
          label: false,
          placeholder: "message",
          wrapper_html: {class: "flex-grow-1"}
        %>
        <%= f.submit "Send", class: "btn btn-accept mb-3" %>
      <% end %>
    </div>
<% else %>
  <div class="header-chat" id= "mom-background">
    <%= cl_image_tag @booking.midwife.photo.key , class: "avatar-large"%>
    <h1><%= @booking.midwife.user.first_name %> <%= @booking.midwife.user.last_name %></h1>
  </div>
  <div class="container chatroom mb-5 pb-5" id="chatroom-mom"
      data-controller="booking-subscription"
      data-booking-subscription-booking-id-value="<%= @booking.id %>">
    <div class="messages" data-booking-subscription-target="messages">
      <% @booking.messages.each do |message| %>
          <%= render "messages/message", message: message %>
      <% end %>
    </div>
      <%= simple_form_for [@booking, @message], html: { data: { action: "turbo:submit-end->booking-subscription#resetForm" }, class: "d-flex" } do |f| %>
        <%= f.input :content,
          label: false,
          placeholder: "Message #",
          wrapper_html: {class: "flex-grow-1"}
        %>
        <%= f.submit "Send", class: "btn btn-accept mb-3" %>
      <% end %>
    </div>
<% end %>