config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'mom_midwife_signup', to: 'pages#new_mom_midwife', as: :new_mom_midwife

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :midwives do
    resources :bookings
  end

  resources :bookings do
    resources :appointments, except: [:destroy]
    resources :messages, only: :create
  end

  resources :appointments, only: [:destroy]
  resources :moms do
    resources :notes, only: [:new, :create]
  end

  resources :notes, only: [:edit, :update, :destroy]

  get 'search', to: 'pages#search', as: :search
  get 'calendar', to: 'pages#calendar', as: :calendar
  get 'chatrooms', to: 'pages#chatrooms', as: :chatrooms
  patch 'bookings/:id/accepted', to: 'bookings#accepted', as: 'accepted'
  patch 'bookings/:id/cancelled', to: 'bookings#cancelled', as: 'cancelled'
  patch 'bookings/:id/cancelled_user', to: 'bookings#cancelled_user', as: 'cancelled_user'
  patch 'bookings/:id/appointments/:id/cancelled_appointment', to: 'appointments#cancelled_appointment', as: 'cancelled_appointment'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
    <% if user_signed_in? && current_user.try(:is_midwife?) %>
      <%= image_tag("logopink.png") %>
    <% else %>
      <%= image_tag("logoblue.png") %>
    <% end %>
    <% end %>

    <div class="" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <div id="right-header" class="image-cropper">
          <% if current_user.try(:is_midwife?) %>
            <%= cl_image_tag current_user.midwife.photo.key, class: "avatar-small"%>
          <% else %>
            <%= cl_image_tag current_user.mom.photo.key, class: "avatar-small-blue"%>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% unless @no_navbar %>
    <% if current_user.is_midwife? %>
      <div class="navbar-fymw" id="navbar-midwife">
        <%= link_to bookings_path do %>
          <i class="fa-solid fa-user-check icon-navbar-midwife"></i>
        <% end  %>
        <%= link_to calendar_path do %>
          <i class="fa-solid fa-calendar-check icon-navbar-midwife"></i>
        <% end %>
          <%= link_to midwives_path do %>
        <i class="fa-solid fa-house icon-navbar-midwife"></i>
          <% end %>
        <%= link_to chatrooms_path do %>
          <i class="fa-solid fa-comment icon-navbar-midwife"></i>
        <% end %>
        <div class="dropup">
          <i class="fa-solid fa-gear icon-navbar-midwife" data-bs-toggle="dropdown" aria-expanded="false"></i>
          <div class="dropdown-menu dropdown-fix">
            <%= button_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete, data: {turbo: false} %>

            <%= button_to 'Profile', midwife_path(current_user.midwife), class: "dropdown-item", method: :get, data: {turbo: false} %>

          </div>
        </div>
      </div>
    <% else %>
      <div class="navbar-fymw" id="navbar-mom">
        <%= link_to search_path do %>
          <i class="fa-solid fa-magnifying-glass icon-navbar-mom"></i>
        <% end %>
        <%= link_to bookings_path do %>
          <i class="fa-solid fa-calendar-check icon-navbar-mom"></i>
        <% end %>
        <%= link_to moms_path do %>
          <i class="fa-solid fa-house icon-navbar-mom"></i>
        <% end %>
        <%= link_to chatrooms_path do %>
          <i class="fa-solid fa-comment icon-navbar-mom"></i>
        <% end %>
        <div class="dropup">
          <i class="fa-solid fa-gear icon-navbar-mom" data-bs-toggle="dropdown" aria-expanded="false"></i>
          <ul class="dropdown-menu dropdown-fix">
            <%= button_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete, data: {turbo: false} %>
            <%= button_to 'Profile', mom_path(current_user.mom), class: "dropdown-item", method: :get, data: {turbo: false} %>
          </ul>
        </div>
      </div>
    <% end %>
  <% end %>