config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'mom_midwife_signup', to: 'pages#new_mom_midwife', as: :new_mom_midwife

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :midwives do
    resources :bookings
  end

  resources :bookings do
    resources :appointments, except: [:destroy]
    resources :messages, only: :create
  end

  resources :appointments, only: [:destroy]
  resources :moms do
    resources :notes, only: [:new, :create]
  end

  resources :notes, only: [:edit, :update, :destroy]

  get 'search', to: 'pages#search', as: :search
  get 'calendar', to: 'pages#calendar', as: :calendar
  get 'chatrooms', to: 'pages#chatrooms', as: :chatrooms
  patch 'bookings/:id/accepted', to: 'bookings#accepted', as: 'accepted'
  patch 'bookings/:id/cancelled', to: 'bookings#cancelled', as: 'cancelled'
  patch 'bookings/:id/cancelled_user', to: 'bookings#cancelled_user', as: 'cancelled_user'
  patch 'bookings/:id/appointments/:id/cancelled_appointment', to: 'appointments#cancelled_appointment', as: 'cancelled_appointment'
end

app/views/pages/calendar.html.erb
<div class="container mt-5 text-center" style="margin-top: 30px !important;">
  <%= month_calendar(events: @appointments) do |date, appointment| %>
      <%= date.day %>
  <% end %>
  <div class="card-container">
    <div class="outer-card-calendar align-items-center mb-5" id="midwife-card">
      <% @moms.each do |mom| %>
          <% mom.bookings.each do |booking| %>
            <% unless booking.appointments.empty? || booking.mom != mom || booking.midwife != current_user.midwife%>
              <div class="outer-card-appointment w-100">
              <%= link_to mom_path(mom), class: "text-decoration-none text-dark", style:"display: flex; align-items: center;" do %>
                <%= cl_image_tag mom.photo.key, class: "avatar-small" %>
                <h4 style="padding-left:10px;"><%= mom.user.first_name %> <%= mom.user.last_name %></h4>
              <% end %>
              <% booking.appointments.each do |appointment| %>
                <div class="inner-card-appointment" style="width:100%; margin-top:8px;">
                  <div>
                  <p class="text-start mb-2" style="margin-left: 5px;"><strong><%= appointment.title %></strong></p>
                  <p style="margin-left: 5px; margin-bottom: 4px;"><%= appointment.start_time.strftime("%A, %d %b %Y %l:%M %p") %></p>
                  </div>
                </div>
              <% end %>
              </div>
              <div class="border"></div>
            <% end %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/chatrooms.html.erb
<% if current_user.is_midwife? %>
  <div class="chatroom-index" id="chatroom-midwife">
    <h1>Chats</h1>
  </div>
  <div class="container">
    <% @bookings.each do |booking| %>
      <% if booking.messages.empty? %>
      <% else %>
        <% if current_user.midwife == booking.midwife %>
        <div class="chatroom-card">
          <div>
            <%= cl_image_tag booking.mom.photo.key , class: "avatar-extra-small"%>
          </div>
          <div class="w-100">
            <div class="chatroom-time">
              <%= link_to booking_path(booking), class: "text-decoration-none" do %>
                <div style= "color: #FC9D9D"><%= booking.mom.user.first_name %></div>
              <% end %>
              <p>
                <%= booking.messages.last.created_at.strftime("%H:%M") %>
              </p>
            </div>
            <div>
              <div>
                <%= truncate(booking.messages.last.content, length: 30) %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
    <% end %>
<% else %>
  <div class="chatroom-index" id="chatroom-mom">
    <h1>Chats</h1>
  </div>
    <% @bookings.each do |booking| %>
      <% if booking.messages.empty? %>
      <% else %>
        <% if current_user.mom == booking.mom %>
        <div class="chatroom-card">
          <div>
            <%= cl_image_tag booking.midwife.photo.key , class: "avatar-extra-small"%>
          </div>
          <div class="w-100">
            <div class="chatroom-time">
              <%= link_to booking_path(booking), class: "text-decoration-none" do %>
                <div style= "color: #A3C7D6"><%= booking.midwife.user.first_name %> </div>
              <% end %>
              <p>
                <%= booking.messages.last.created_at.strftime("%H:%M") %>
              </p>
            </div>
            <div>
              <div>
                <%= truncate(booking.messages.last.content, length: 30) %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/new_mom_midwife.html.erb
<% if !current_user.is_midwife %>
  <%= simple_form_for @mom do |f| %>
    <%= f.input :due_date, as: :date, html5: true, class: 'btn btn-flat'%>
    <%= f.input :phone , class: 'btn btn-flat' %>
    <%= f.input :photo, as: :file, class: 'btn btn-flat' %>
    <%= f.submit class: 'btn btn-flat' %>
  <% end %>
<% else %>
  <%= simple_form_for @midwife do |f| %>
    <%= f.label :speciality%>
    <br>
    <%= f.select :speciality, Midwife::SPECIALITIES%>
    <%= f.input :years_experience , class: 'btn btn-flat' %>
    <%= f.input :availability, as: :date, html5: true, class: 'btn btn-flat' %>
    <%= f.input :photo, as: :file, class: 'btn btn-flat' %>
    <%= f.submit class: 'btn btn-flat' %>
  <% end %>
<% end %>

app/views/pages/search.html.erb
<div class="container" style="margin-bottom:60px;">
  <% if @midwives.empty? %>
    <div>
      <p>There are no midwives currently available</p>
    </div>
  <% else %>
    <button type="button" class="btn btn-blue mt-3" data-bs-toggle="modal" data-bs-target="#filter">
      <div class="d-flex align-items-center">
        <div class="pe-2">
          <i class="fa-solid fa-filter"></i>
        </div>
        Filter
      </div>
    </button>
      <div class="modal fade" id="filter" tabindex="-1" aria-labelledby="filter" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Filters</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <%# <div class="modal-body"> %>
              <%# <strong><p>Speciality</p></strong> %>
              <div data-controller="filter-midwives">
                <%= form_tag search_path, { method: :get } do %>
                  <div class="modal-body">
                    <strong><p>Speciality</p></strong>
                    <% Midwife::SPECIALITIES.each do |speciality| %>
                      <div class="checkboxes">
                        <%= check_box_tag 'selected_specialities[]', speciality %>
                        <%= label_tag(speciality) %>
                      </div>
                    <% end %>
                  </div>
                  <div class="modal-footer">
                    <%= submit_tag "Search by filter", class: "btn btn-blue" %>
                    <%# <button type="button" class="btn btn-accept">Search by filters</button> %>
                    <button type="button" class="btn btn-white" data-bs-dismiss="modal">Close</button>
                  </div>
                  <%# <div style="display:none;">
                  <%# submit_tag %>
                  <%# </div> %>
                <% end %>
              </div>
            <%# </div> %>
            <%# <div class="modal-footer">
              <button type="button" class="btn btn-accept" data-bs-dismiss="modal">Search by filters</button>
              <button type="button" class="btn btn-deny" data-bs-dismiss="modal">Close</button>
            </div> %>
          </div>
        </div>
      </div>
    <% @midwives.each do |midwife| %>
      <div class="outer-card mt-3" data-filter-midwives-target="list">
        <div class="inner-card" id="mom-card">
          <h5 class="card-title"> <%= cl_image_tag midwife.photo.key, class: "avatar-large"%> <strong><%= midwife.user.first_name %> <%= midwife.user.last_name %></h5></strong>
          <p class="card-text" style="padding-top: 5px;"><strong>Speciality: </strong><%= midwife.speciality %> <br> <strong>Experience: </strong><%= midwife.years_experience %> years</p>
          <p><%= link_to 'Send Request', midwife_bookings_path(midwife),  data: {turbo_method: :post}, class: 'btn btn-blue' %>     <%= link_to 'View Profile', midwife_path(midwife) , class: "btn btn-blue" %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>