config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'mom_midwife_signup', to: 'pages#new_mom_midwife', as: :new_mom_midwife

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :midwives do
    resources :bookings
  end

  resources :bookings do
    resources :appointments, except: [:destroy]
    resources :messages, only: :create
  end

  resources :appointments, only: [:destroy]
  resources :moms do
    resources :notes, only: [:new, :create]
  end

  resources :notes, only: [:edit, :update, :destroy]

  get 'search', to: 'pages#search', as: :search
  get 'calendar', to: 'pages#calendar', as: :calendar
  get 'chatrooms', to: 'pages#chatrooms', as: :chatrooms
  patch 'bookings/:id/accepted', to: 'bookings#accepted', as: 'accepted'
  patch 'bookings/:id/cancelled', to: 'bookings#cancelled', as: 'cancelled'
  patch 'bookings/:id/cancelled_user', to: 'bookings#cancelled_user', as: 'cancelled_user'
  patch 'bookings/:id/appointments/:id/cancelled_appointment', to: 'appointments#cancelled_appointment', as: 'cancelled_appointment'
end

app/controllers/midwives_controller.rb
class MidwivesController < ApplicationController
  before_action :set_mom, only: [ ]
  before_action :set_midwife, only: [ :show, :update]

  def index
    return redirect_to moms_path unless current_user.is_midwife

    if current_user.midwife.upcoming_appointment
      @mom_user = current_user.midwife.upcoming_appointment.booking.mom.user
      @markers = [
        {
          lat: @mom_user.latitude,
          lng: @mom_user.longitude
        }
      ]
    end
  end

  def show; end

  def new
    @midwife = Midwife.new
  end

  def create
    @midwife = Midwife.new(midwife_params)
    @midwife.user = current_user
    if @midwife.save
      redirect_to midwives_path
    else
      render :new
    end
  end

  def update
    @midwife.update(midwife_params)
    if @midwife.save
      redirect_to midwife_path(@midwife)
    else
      render 'midwives/show', status: :unprocessable_entity
    end
  end

  def destroy
    @midwife.destroy
    redirect_to root_path
  end

  private

  def set_mom
    @mom = Mom.find(params[:mom_id])
  end

  def set_midwife
    @midwife = Midwife.find(params[:id])
  end

  def midwife_params
    params.require(:midwife).permit(:speciality, :years_experience, :availability, :photo, :bio)
  end
end

app/views/midwives/index.html.erb
<div>
  <div class="index-header" style="margin-left: -70px;">
    <div>
      <h1 style="font-weight: 300;">Hello, </h1>
      <h1 style="font-weight: 500;color: #FC9D9D;"><%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %>!</h1>
    </div>
  </div>
  <div>
    <div class="container">
      <div class="outer-card mb-3 pb-0" id="midwife-card">
        <div class="background-card background-h3 pb-0">
          <h2>Upcoming Appointment</h2>
          <%= link_to calendar_path, class: "link-pink" do %>
            <h3 style="font-weight: bold">See all</h3>
          <% end %>
        </div>
        <% if !current_user.midwife.upcoming_appointment.nil? %>
          <div class="inner-card pt-0">
              <div class="name-avatar">
                <%= cl_image_tag current_user.midwife.upcoming_appointment.booking.mom.photo.key , class: "avatar"%>
                <h4><%= current_user.midwife.upcoming_appointment.booking.mom.user.first_name %> <%= current_user.midwife.upcoming_appointment.booking.mom.user.last_name %>: <%= current_user.midwife.upcoming_appointment.title %></h4>
              </div>
              <div class="border"></div>
              <div class="info-card">
                <h5><i class="fa fa-clock" style="color:#FC9D9D"></i> <%= current_user.midwife.upcoming_appointment.start_time.strftime("%A, %d %b %Y %l:%M %p") %> </h5>
                <h5><i class="fa fa-location-dot" style="color:#FC9D9D"></i>  <%= current_user.midwife.upcoming_appointment.booking.mom.user.address %> </h5>
              </div>
              <div style="width: 100%; height: 200px;"
              data-controller="map"
              data-map-markers-value="<%= @markers.to_json %>"
              data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
              </div>
            </div>
          </div>
        <% else %>
          <p>You have no upcoming appointment</p>
        <% end %>
      </div>
    </div>
      <div class="container pb-5">
      <div class="outer-card mb-4" id="midwife-card">
        <div class="background-card pb-0">
          <h2>New Requests</h2>
        </div>
        <% if !current_user.midwife.new_requests.nil? %>
          <div class="inner-card pt-0 pb-0">
            <div class="name-avatar">
              <%= cl_image_tag current_user.midwife.new_requests.mom.photo.key , class: "avatar"%>
              <h4><%= current_user.midwife.new_requests.mom.user.first_name %> <%= current_user.midwife.new_requests.mom.user.last_name %></h4>
            </div>
            <div class="border"></div>
            <div class="info-card">
              <h5><i class="fa fa-solid fa-baby" style="color:#FC9D9D"></i> Due Date: <%= current_user.midwife.new_requests.mom.due_date %> </h5>
              <h5><i class="fa fa-location-dot" style="color:#FC9D9D"></i>  <%= current_user.midwife.new_requests.mom.user.address%> </h5>
              <div class="d-flex justify-content-between mt-3">
              <p><%= link_to 'Accept', accepted_path(current_user.midwife.new_requests), data: { turbo_method: :patch}, class: "btn btn-accept"%>   <%= link_to 'Deny', cancelled_path(current_user.midwife.new_requests), data: { turbo_method: :patch}, class: "btn btn-deny" %></p>
              </div>
            </div>
          </div>
        <% else %>
          <p>no current requests</p>
        <% end %>
      </div>
    </div>
    </div>
</div>

app/views/midwives/show.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<div class="container">
  <% if current_user.is_midwife? %>
    <div class="inner-card" id="midwife-card" style="margin-top: 20px;margin-bottom: 60px;">
  <% else %>
    <div class="inner-card" id="mom-card" style="margin-top: 20px; padding-top: 5px; margin-bottom: 60px;">
  <% end %>
      <% if current_user.is_midwife? %>
        <div class="midwife-info-card">
      <% else %>
        <div class="mom-info-card">
      <% end %>
        <%= cl_image_tag @midwife.photo.key, class:"extra-large-avatar center mt-2"%>
        <p style="padding-top: 20px;"><i class="fa fa-user" style="color: #FFCAC2"></i> <strong><%= @midwife.user.first_name %> <%= @midwife.user.last_name %></strong></p>
        <p></p>
        <p><i class="fa-regular fa-calendar-days" style="color: #FFCAC2"></i>  Available: <%= @midwife.availability.strftime("%d/%m/%Y")%></p>
        <p><i class="fa-solid fa-star" style="color: #FFCAC2"></i> <%= @midwife.speciality%> - <%= @midwife.years_experience %> years</p>
        <p style="text-align: justify;"> <%= @midwife.bio %></p>

      <% if current_user.is_midwife && current_user.midwife = @midwife %>
          <button type="button" class="btn btn-accept" data-bs-toggle="modal" data-bs-target="#profile">
              Edit Profile
            </button>

            <!-- Modal -->
            <div class="modal fade" id="profile" tabindex="-1" aria-labelledby="noteModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Edit profile</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <%= simple_form_for(@midwife) do |f| %>
                    <%= f.select :speciality, Midwife::SPECIALITIES%>
                    <%= f.input :years_experience , class: 'btn btn-flat' %>
                    <%= f.input :availability, as: :date, html5: true, class: 'btn btn-flat' %>
                    <%= f.input :photo, as: :file, class: 'btn btn-flat' %>
                    <%= f.submit class: "btn btn-outline-info" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
      <% else %>
        <%= link_to 'Send Request', midwife_bookings_path(@midwife),  data: {turbo_method: :post}, class: 'btn btn-blue', style:"justify-content: left;width: 100%;" %>
        <%= link_to search_path, class: 'btn-ghost-blue' do %>
        <div class="d-flex align-items-center" style="margin-top: 20px;">
          <i class="fa-solid fa-arrow-left pe-2"></i>
            Back
        </div>
        <% end %>
      <% end %>
    </div>
</div>